### PR TITLE
#37 Custom `pathFunc`

### PR DESCRIPTION
**Pull request by Emsu**

### CODE REVIEW

**Comment by bkrem** [comment]
Hey @Emsu, thanks for this PR! 😄  Looks great so far, both features that will be useful to most people using the library.

Going to have a quick check over it this afternoon, then hopefully get this merged, documented and released 🚀

**Comment by bkrem** [comment]
Could you explain a specific use case for #36? 
I've tested `nodeSvgShape.children` with a few elements (e.g. `rect`, `text`); they appear in the DOM correctly as the child of each node shape but they don't seem to be painted on the SVG canvas/aren't located anywhere on the canvas :/

**Comment by Emsu** [comment]
@bkrem For #36 I'm trying to make it so I can build multiple org hierarchies where the nodes are complex elements with text and other images. I haven't actually tried to build it out yet though, thought I would add it to the library first.

Maybe I need to look into the svgs a little more. Also I haven't checked if the data on each node is available to the children as props which I'll need to build out my use case.

**Comment by bkrem** [comment]
@Emsu yeah that would be amazing, happy to help you get #36 working!
I’d suggest to split the two features into separate PRs so we can merge #37 now and #36 when there’s a stable implementation :+1:

**Comment by Emsu** [comment]
@bkrem updated this PR to be just #37

**Comment by Emsu** [comment]
@bkrem Also added `package-lock.json`. Not sure what version of `npm` you're running but I think the latest ones all use this lock file.

**Comment by bkrem** [comment]
Thanks for splitting the two features! There's already a `yarn.lock` but yeah why not, make life easier for the NPM users 👍

**Pull request merged**
