### PR TITLE
New feature: "straight" as a pathFunc

### PR DESCRIPTION
**Pull request by justinsisley**
I was interested in seeing what a "straight" pathFunc would look like, and while I don't have any experience using D3, I was able to cobble something together.

I like the end result, and it works nicely for one of my use cases.

Let me know what you think, and if there are any changes that I need to make. Thanks!

### CODE REVIEW

**Comment by justinsisley** [comment]
Fail. Looks like this has caused the test coverage threshold to drop below the acceptable level.

**Comment by justinsisley** [comment]
I've added a test case for straightPath that was really an obvious miss on my part, but now that jest is happy, coveralls isn't. I'll see what else I can get coverage on.

**Comment by justinsisley** [comment]
I've converted the `switch/case` inside of the `drawPath` method to `if` conditions. This improves the code coverage, since the `default` case is considered a new potential execution branch.

I think `if` conditions are fine here, since there probably can't be too many (if any) more pathFunc's that could be implemented.

Let me know what you think.

**Comment by bkrem** [comment]
This looks great @justinsisley, thanks for implementing this path function! 😄 

I'm happy to reduce the branching threshold if a `switch` makes more sense here. The thresholds are primarily there to prevent regressions which doesn't apply to a simple `default` case.

Currently at work, so will check over this/merge this evening 👍

**Comment by bkrem** [comment]
Published as [v1.4.0](https://github.com/bkrem/react-d3-tree/releases/tag/v1.4.0) 🚀 

Thanks again for this awesome feature and the clean code! ✨

**Pull request merged**
