### PR TITLE
add onMouseOver feature

### PR DESCRIPTION
**Pull request by RohanDamani**
I was unsure how to test this.  How are you running the environment locally?  

I copied the format of the onClick handler, let me know if I should add to the test files or ReadME, or what you need.  I didn't include in "Node  index.test.js" because its an optional prop, but I'm seeing that reduced coverall coverage.

I ran `npm run dev` and it gave me an error that onFocus must accompany onMouseOver for accessibility reasons, so I added onFocus as well.

Let me know

### CODE REVIEW

**Comment by bkrem** [comment]
Hey @RohanDamani,

Nice work man, thank you for doing this! 👏 👏 

No worries about the testing if it was confusing (sorry about that), I'll have a look later and will add a test. 

I'm going to finally add a Contributing section with instructions/common commands later today when I merge this, along with the example/debug React app I'm using for the demo. That should make future contributions a lot easier/quicker :)

**Comment by RohanDamani** [comment]
how are you running the project locally?

By 'not testing' I mean I was not able to run it see if it worked (in addition to not adding to the tests).  I wasn't sure how to spin up the project locally, besides importing it into another project and trying it out there.  I'm used to create-react-app with a local server built in a and 'npm start'.  Is there a way to spin up the tree in a test env?

**Comment by bkrem** [comment]
@RohanDamani 

Finally had the time to get this set up properly, here's the debug/demo application: https://github.com/bkrem/react-d3-tree-demo

All you should have to do is clone it + run `bash ./setup.sh` inside the repo. After that you should be good to go 👍 

Let me know how you want to move forward with this PR if it's still work-in-progress in your eyes/you want to add tests. Otherwise I can take a look myself, merge + add tests.

**Comment by bkrem** [comment]
@RohanDamani gonna finish this up and get it into a release. Will let you know in the linked issue when it's been released :)

**Comment by RohanDamani** [comment]
@bkrem fantastic -- will contribute more as I get the chance!

fyi I'm getting `bash: ./setup.sh: No such file or directory` what does this setup script do?

**Comment by RohanDamani** [comment]
@bkrem fantastic -- will contribute more as I get the chance!

fyi I'm getting `bash: ./setup.sh: No such file or directory` what does this setup script do?

**Pull request merged**
