### PR TITLE
Individual node shapes

### PR DESCRIPTION
**Pull request by sspanak**
Hi, @bkrem, here comes another improvement. This one allows for settings "nodeSvgShape" for each node individually, thus making it possible to set shape, size and style for each node. I think it is similar to #35, but I am not completely sure.

The code change is minimal, however styles have to be part of the input data (optionally, of course). I hope you like the idea.

As usual, I have updated unit tests and the documentation.

### CODE REVIEW

**Comment by bkrem** [comment]
Hey @sspanak,

Sorry I’ve been on a work related trip the past few days. This looks pretty much perfect, very elegant solution to the problem!

Will review properly on a big screen when I’m home and get this released 🚀

**Comment by sspanak** [comment]
Thanks, @bkrem. I am looking forward to the release.

**Comment by bkrem** [comment]
Hey @sspanak,

Made some small naming adjustments and fixed a minor bug we had left over with the merge order of the styles: https://github.com/bkrem/react-d3-tree/commit/7424903e1062d5f602ccb8e65badd37b0dd8e671

Let me know if this is all above board for you and I'll get a release rolled out :)

**Comment by sspanak** [comment]
Yes, it looks good. I was hesitating to name the property `nodeSvgShape` or not, anyway. 
And... as for merging the properties - good catch. :+1:

**Comment by bkrem** [comment]
Released in [v1.10.0](https://github.com/bkrem/react-d3-tree/releases/tag/v1.10.0) 🚀

**Pull request merged**
