### PR TITLE
fix: treat node with empty children as leaf

### PR DESCRIPTION
**Pull request by zhouhao**
Hello @bkrem, thank you for your great package.

I feel it makes more sense here to treat node with empty children as leaves.
WDYT?

### CODE REVIEW

**Comment by bkrem** [comment]
Hi @zhouhao,

Sorry about the wait, it's been a very busy week.

Agreed and this all looks great! Will try to get a patch release out for this in the next 24hrs.

I also think there is an issue open for this, which I'll link.

**Comment by zhouhao** [comment]
Thank you @bkrem ! No worries. ;-)

https://github.com/bkrem/react-d3-tree/issues/395

**Review by bkrem — APPROVED** [review]

**Comment by bkrem** [comment]
Closes #395

**Comment by bkrem** [comment]
Published as https://github.com/bkrem/react-d3-tree/releases/tag/v3.3.5

Thanks again for the fix! 🙌

**Pull request merged**
